version: '3'
services:
  bincollection_bot:
    depends_on:
      - redis
    build: .
    volumes:
      - .:/bincollection_bot

  redis:
    image: redis:6-alpine
    restart: on-failure
    volumes:
      - redis-db:/data
    ports:
      - 6363:6379

volumes:
  redis-db: